### PR TITLE
Add support for Kotlin

### PR DESCRIPTION
**Pull request by lucko**
#4 

Needs testing.

### CODE REVIEW

**Comment by STG-Allen** [comment]
Upon testing this PR I came across an issue where a ``Remodification`` error is thrown, even without modifying the files. Perhaps there's another approach to take for Kotlin?

**Comment by STG-Allen** [comment]
@kashike 
Here is the error: 
```
> Task :playerbalancer-api:compileKotlin FAILED
e: C:\Users\Allen\IdeaProjects\PlayerBalancer\playerbalancer-api\build\sources\kotlin\org\anvilpowered\playerbalancer\api\PlayerBalancer.kt: (9, 12): Redeclaration: PlayerBalancer
e: C:\Users\Allen\IdeaProjects\PlayerBalancer\playerbalancer-api\build\sources\kotlin\org\anvilpowered\playerbalancer\api\plugin\PluginMessages.kt: (6, 7): Redeclaration: PluginMessages
e: C:\Users\Allen\IdeaProjects\PlayerBalancer\playerbalancer-api\build\sources\kotlin\org\anvilpowered\playerbalancer\api\registry\PlayerBalancerKeys.kt: (7, 7): Redeclaration: PlayerBalancerKeys
e: C:\Users\Allen\IdeaProjects\PlayerBalancer\playerbalancer-api\src\main\kotlin\org\anvilpowered\playerbalancer\api\PlayerBalancer.kt: (9, 12): Redeclaration: PlayerBalancer
e: C:\Users\Allen\IdeaProjects\PlayerBalancer\playerbalancer-api\src\main\kotlin\org\anvilpowered\playerbalancer\api\plugin\PluginMessages.kt: (6, 7): Redeclaration: PluginMessages
e: C:\Users\Allen\IdeaProjects\PlayerBalancer\playerbalancer-api\src\main\kotlin\org\anvilpowered\playerbalancer\api\registry\PlayerBalancerKeys.kt: (7, 7): Redeclaration: PlayerBalancerKeys
```

Here's `PlayerBalancer.kt`

```
open class PlayerBalancer protected constructor(name: String, rootInjector: Injector, module: Module)
    : BasePlugin(name, rootInjector, module) {

    lateinit var environment: Environment

    fun getRegistry(): Registry {
        return environment.registry
    }
}
```

**Comment by Cubxity** [comment]
Are there any updates on this PR/issue?

**Comment by jpenilla** [comment]
> @kashike
> Here is the error:
> 
> ```
> > Task :playerbalancer-api:compileKotlin FAILED
> e: C:\Users\Allen\IdeaProjects\PlayerBalancer\playerbalancer-api\build\sources\kotlin\org\anvilpowered\playerbalancer\api\PlayerBalancer.kt: (9, 12): Redeclaration: PlayerBalancer
> e: C:\Users\Allen\IdeaProjects\PlayerBalancer\playerbalancer-api\build\sources\kotlin\org\anvilpowered\playerbalancer\api\plugin\PluginMessages.kt: (6, 7): Redeclaration: PluginMessages
> e: C:\Users\Allen\IdeaProjects\PlayerBalancer\playerbalancer-api\build\sources\kotlin\org\anvilpowered\playerbalancer\api\registry\PlayerBalancerKeys.kt: (7, 7): Redeclaration: PlayerBalancerKeys
> e: C:\Users\Allen\IdeaProjects\PlayerBalancer\playerbalancer-api\src\main\kotlin\org\anvilpowered\playerbalancer\api\PlayerBalancer.kt: (9, 12): Redeclaration: PlayerBalancer
> e: C:\Users\Allen\IdeaProjects\PlayerBalancer\playerbalancer-api\src\main\kotlin\org\anvilpowered\playerbalancer\api\plugin\PluginMessages.kt: (6, 7): Redeclaration: PluginMessages
> e: C:\Users\Allen\IdeaProjects\PlayerBalancer\playerbalancer-api\src\main\kotlin\org\anvilpowered\playerbalancer\api\registry\PlayerBalancerKeys.kt: (7, 7): Redeclaration: PlayerBalancerKeys
> ```
> 
> Here's `PlayerBalancer.kt`
> 
> ```
> open class PlayerBalancer protected constructor(name: String, rootInjector: Injector, module: Module)
>     : BasePlugin(name, rootInjector, module) {
> 
>     lateinit var environment: Environment
> 
>     fun getRegistry(): Registry {
>         return environment.registry
>     }
> }
> ```

This seems to be due to Kotlin adding sources to the compile task after blossom is applied. Registering our tasks after the project is evaluated seems to have solved this for me locally. Able to test again @STG-Allen ?

**Review by jpenilla — APPROVED** [review]

**Pull request merged**
